"""Create skills_master and related_skills tables.

Revision ID: 0d6c76e02932
Revises: None
Create Date: 2016-06-15 23:22:54.767072

"""

# revision identifiers, used by Alembic.
revision = '0d6c76e02932'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('related_skills',
    sa.Column('skill_uuid', sa.Integer(), nullable=False),
    sa.Column('related_skills', postgresql.JSONB(), nullable=True),
    sa.PrimaryKeyConstraint('skill_uuid')
    )
    op.create_table('skills_master',
    sa.Column('skill_uuid', sa.Integer(), nullable=False),
    sa.Column('onet_soc_code', sa.String(), nullable=True),
    sa.Column('onet_element_id', sa.String(), nullable=True),
    sa.Column('skill_name', sa.String(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('skill_uuid')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skills_master')
    op.drop_table('related_skills')
    ### end Alembic commands ###
