"""empty message

Revision ID: 3e88156664e1
Revises: 3a1028f9d733
Create Date: 2016-07-17 00:24:29.627249

"""

# revision identifiers, used by Alembic.
revision = '3e88156664e1'
down_revision = '3a1028f9d733'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills_master', sa.Column('skill_name', sa.String(), nullable=True))
    op.drop_column('skills_master', 'onet_ksa')
    op.drop_column('skills_master', 'onet_soc_code')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills_master', sa.Column('onet_soc_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('skills_master', sa.Column('onet_ksa', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('skills_master', 'skill_name')
    ### end Alembic commands ###
