"""empty message

Revision ID: 40f2531a009a
Revises: 3e88156664e1
Create Date: 2016-09-17 23:48:59.224410

"""

# revision identifiers, used by Alembic.
revision = '40f2531a009a'
down_revision = '3e88156664e1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills_importance',
    sa.Column('job_uuid', sa.String(), nullable=False),
    sa.Column('skill_uuid', sa.String(), nullable=False),
    sa.Column('level', sa.Float(), nullable=True),
    sa.Column('importance', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['job_uuid'], ['jobs_master.uuid'], ),
    sa.ForeignKeyConstraint(['skill_uuid'], ['skills_master.uuid'], ),
    sa.PrimaryKeyConstraint('job_uuid', 'skill_uuid')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skills_importance')
    ### end Alembic commands ###
