"""empty message

Revision ID: 4c7ffc4b5b09
Revises: 502662155e36
Create Date: 2016-07-14 23:41:31.687999

"""

# revision identifiers, used by Alembic.
revision = '4c7ffc4b5b09'
down_revision = '502662155e36'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs_master', sa.Column('nlp_a', sa.String(), nullable=True))
    op.add_column('jobs_master', sa.Column('original_title', sa.String(), nullable=True))
    op.add_column('skills_master', sa.Column('description', sa.String(), nullable=True))
    op.add_column('skills_master', sa.Column('nlp_a', sa.String(), nullable=True))
    op.add_column('skills_master', sa.Column('onet_ksa', sa.String(), nullable=True))
    op.drop_column('skills_master', 'count')
    op.drop_column('skills_master', 'skill_name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills_master', sa.Column('skill_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('skills_master', sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('skills_master', 'onet_ksa')
    op.drop_column('skills_master', 'nlp_a')
    op.drop_column('skills_master', 'description')
    op.drop_column('jobs_master', 'original_title')
    op.drop_column('jobs_master', 'nlp_a')
    ### end Alembic commands ###
