"""empty message

Revision ID: 502662155e36
Revises: 838b8a109034
Create Date: 2016-06-30 01:26:07.563294

"""

# revision identifiers, used by Alembic.
revision = '502662155e36'
down_revision = '838b8a109034'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs_skills',
    sa.Column('job_uuid', sa.String(), nullable=False),
    sa.Column('skill_uuid', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['job_uuid'], ['jobs_master.uuid'], ),
    sa.ForeignKeyConstraint(['skill_uuid'], ['skills_master.uuid'], ),
    sa.PrimaryKeyConstraint('job_uuid', 'skill_uuid')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs_skills')
    ### end Alembic commands ###
