"""empty message

Revision ID: 838b8a109034
Revises: b6ad26785b00
Create Date: 2016-06-30 01:09:14.405947

"""

# revision identifiers, used by Alembic.
revision = '838b8a109034'
down_revision = 'b6ad26785b00'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs_unusual_titles', sa.Column('description', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs_unusual_titles', 'description')
    ### end Alembic commands ###
