"""Creation of skills_master, related_skills, and job_skills tables

Revision ID: 87b84686d67d
Revises: None
Create Date: 2016-06-17 01:53:49.628939

"""

# revision identifiers, used by Alembic.
revision = '87b84686d67d'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_skills',
    sa.Column('skill_uuid', sa.String(), nullable=False),
    sa.Column('related_jobs', postgresql.JSONB(), nullable=True),
    sa.PrimaryKeyConstraint('skill_uuid')
    )
    op.create_table('related_skills',
    sa.Column('skill_uuid', sa.String(), nullable=False),
    sa.Column('related_skills', postgresql.JSONB(), nullable=True),
    sa.PrimaryKeyConstraint('skill_uuid')
    )
    op.create_table('skills_master',
    sa.Column('skill_uuid', sa.String(), nullable=False),
    sa.Column('onet_soc_code', sa.String(), nullable=True),
    sa.Column('onet_element_id', sa.String(), nullable=True),
    sa.Column('skill_name', sa.String(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('skill_uuid')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skills_master')
    op.drop_table('related_skills')
    op.drop_table('job_skills')
    ### end Alembic commands ###
