"""Added job skills table

Revision ID: 8965956d3ce8
Revises: 0d6c76e02932
Create Date: 2016-06-17 00:15:06.359113

"""

# revision identifiers, used by Alembic.
revision = '8965956d3ce8'
down_revision = '0d6c76e02932'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_skills',
    sa.Column('onet_soc_code', sa.String(), nullable=False),
    sa.Column('related_skills', postgresql.JSONB(), nullable=True),
    sa.PrimaryKeyConstraint('onet_soc_code')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_skills')
    ### end Alembic commands ###
