"""empty message

Revision ID: b6ad26785b00
Revises: bc3dd5c62a9e
Create Date: 2016-06-29 23:46:34.915792

"""

# revision identifiers, used by Alembic.
revision = 'b6ad26785b00'
down_revision = 'bc3dd5c62a9e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs_unusual_titles',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('job_uuid', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['job_uuid'], ['jobs_master.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs_unusual_titles')
    ### end Alembic commands ###
