"""empty message

Revision ID: bc3dd5c62a9e
Revises: None
Create Date: 2016-06-26 08:23:42.413609

"""

# revision identifiers, used by Alembic.
revision = 'bc3dd5c62a9e'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs_master',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('onet_soc_code', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('skills_master',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('onet_soc_code', sa.String(), nullable=True),
    sa.Column('onet_element_id', sa.String(), nullable=True),
    sa.Column('skill_name', sa.String(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('skills_related',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('related_skills', postgresql.JSONB(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('jobs_alternate_titles',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('job_uuid', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['job_uuid'], ['jobs_master.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs_alternate_titles')
    op.drop_table('skills_related')
    op.drop_table('skills_master')
    op.drop_table('jobs_master')
    ### end Alembic commands ###
